version: "3"
services:

  web:
    build: .
    command: python news_board/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "hv&DGV&(DSVFd97VFDS&(BVAUG79D"
      DB_HOST: "postgres"
      DEBUG: "false"

  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: "hv&DGV&(DSVFd97VFDS&(BVAUG79D"
